config/routes.rb
Rails.application.routes.draw do
  resources :matchups
  resources :moves
  resources :pokemon_types
  resources :pokemon
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/pokemon_types_controller.rb
class PokemonTypesController < ApplicationController
  before_action :set_pokemon_type, only: [:show, :edit, :update, :destroy]

  # GET /pokemon_types
  # GET /pokemon_types.json
  def index
    @pokemon_types = PokemonType.all
  end

  # GET /pokemon_types/1
  # GET /pokemon_types/1.json
  def show
  end

  # GET /pokemon_types/new
  def new
    @pokemon_type = PokemonType.new
  end

  # GET /pokemon_types/1/edit
  def edit
  end

  # POST /pokemon_types
  # POST /pokemon_types.json
  def create
    @pokemon_type = PokemonType.new(pokemon_type_params)

    respond_to do |format|
      if @pokemon_type.save
        format.html { redirect_to @pokemon_type, notice: 'Pokemon type was successfully created.' }
        format.json { render :show, status: :created, location: @pokemon_type }
      else
        format.html { render :new }
        format.json { render json: @pokemon_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemon_types/1
  # PATCH/PUT /pokemon_types/1.json
  def update
    respond_to do |format|
      if @pokemon_type.update(pokemon_type_params)
        format.html { redirect_to @pokemon_type, notice: 'Pokemon type was successfully updated.' }
        format.json { render :show, status: :ok, location: @pokemon_type }
      else
        format.html { render :edit }
        format.json { render json: @pokemon_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemon_types/1
  # DELETE /pokemon_types/1.json
  def destroy
    @pokemon_type.destroy
    respond_to do |format|
      format.html { redirect_to pokemon_types_url, notice: 'Pokemon type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon_type
      @pokemon_type = PokemonType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pokemon_type_params
      params.require(:pokemon_type).permit(:name)
    end
end

app/helpers/pokemon_types_helper.rb
module PokemonTypesHelper
end

app/views/pokemon_types/_form.html.erb
<%= form_with(model: pokemon_type, local: true) do |form| %>
  <% if pokemon_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pokemon_type.errors.count, "error") %> prohibited this pokemon_type from being saved:</h2>

      <ul>
        <% pokemon_type.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pokemon_types/edit.html.erb
<h1>Editing Pokemon Type</h1>

<%= render 'form', pokemon_type: @pokemon_type %>

<%= link_to 'Show', @pokemon_type %> |
<%= link_to 'Back', pokemon_types_path %>

app/views/pokemon_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pokemon Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pokemon_types.each do |pokemon_type| %>
      <tr>
        <td><%= pokemon_type.name %></td>
        <td><%= link_to 'Show', pokemon_type %></td>
        <td><%= link_to 'Edit', edit_pokemon_type_path(pokemon_type) %></td>
        <td><%= link_to 'Destroy', pokemon_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pokemon Type', new_pokemon_type_path %>

app/views/pokemon_types/new.html.erb
<h1>New Pokemon Type</h1>

<%= render 'form', pokemon_type: @pokemon_type %>

<%= link_to 'Back', pokemon_types_path %>

app/views/pokemon_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pokemon_type.name %>
</p>

<%= link_to 'Edit', edit_pokemon_type_path(@pokemon_type) %> |
<%= link_to 'Back', pokemon_types_path %>