config/routes.rb
Rails.application.routes.draw do
  resources :matchups
  resources :moves
  resources :pokemon_types
  resources :pokemon
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/move.rb
class Move < ApplicationRecord
	has_and_belongs_to_many :pokemon
	belongs_to :pokemon_type

	attr_accessor :stab

	def	dps
		power / ( cooldown / 1000.0 ).to_f * ( stab ? 1.25 : 1 )
	end

	def	eps
		energy / ( cooldown / 1000.0).to_f
  end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  before_action :set_move, only: [:show, :edit, :update, :destroy]

  # GET /moves
  # GET /moves.json
  def index
    @moves = Move.all
  end

  # GET /moves/1
  # GET /moves/1.json
  def show
  end

  # GET /moves/new
  def new
    @move = Move.new
  end

  # GET /moves/1/edit
  def edit
  end

  # POST /moves
  # POST /moves.json
  def create
    @move = Move.new(move_params)

    respond_to do |format|
      if @move.save
        format.html { redirect_to @move, notice: 'Move was successfully created.' }
        format.json { render :show, status: :created, location: @move }
      else
        format.html { render :new }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moves/1
  # PATCH/PUT /moves/1.json
  def update
    respond_to do |format|
      if @move.update(move_params)
        format.html { redirect_to @move, notice: 'Move was successfully updated.' }
        format.json { render :show, status: :ok, location: @move }
      else
        format.html { render :edit }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moves/1
  # DELETE /moves/1.json
  def destroy
    @move.destroy
    respond_to do |format|
      format.html { redirect_to moves_url, notice: 'Move was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_move
      @move = Move.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def move_params
      params.require(:move).permit(:name, :pokemon_type_id, :category, :power, :energy, :cooldown, :pvp_power, :pvp_energy, :pvp_turns, :weather, :damage_window_min, :damage_window_max)
    end
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/views/moves/_form.html.erb
<%= form_with(model: move, local: true) do |form| %>
  <% if move.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(move.errors.count, "error") %> prohibited this move from being saved:</h2>

      <ul>
        <% move.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :pokemon_type_id %>
    <%= form.number_field :pokemon_type_id %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :power %>
    <%= form.number_field :power %>
  </div>

  <div class="field">
    <%= form.label :energy %>
    <%= form.number_field :energy %>
  </div>

  <div class="field">
    <%= form.label :cooldown %>
    <%= form.number_field :cooldown %>
  </div>

  <div class="field">
    <%= form.label :pvp_power %>
    <%= form.number_field :pvp_power %>
  </div>

  <div class="field">
    <%= form.label :pvp_energy %>
    <%= form.number_field :pvp_energy %>
  </div>

  <div class="field">
    <%= form.label :pvp_turns %>
    <%= form.number_field :pvp_turns %>
  </div>

  <div class="field">
    <%= form.label :weather %>
    <%= form.text_field :weather %>
  </div>

  <div class="field">
    <%= form.label :damage_window_min %>
    <%= form.number_field :damage_window_min %>
  </div>

  <div class="field">
    <%= form.label :damage_window_max %>
    <%= form.number_field :damage_window_max %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/moves/edit.html.erb
<h1>Editing Move</h1>

<%= render 'form', move: @move %>

<%= link_to 'Show', @move %> |
<%= link_to 'Back', moves_path %>

app/views/moves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Moves</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pokemon type</th>
      <th>Category</th>
      <th>Power</th>
      <th>Energy</th>
      <th>Cooldown</th>
      <th>Pvp power</th>
      <th>Pvp energy</th>
      <th>Pvp turns</th>
      <th>Weather</th>
      <th>Damage window min</th>
      <th>Damage window max</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @moves.each do |move| %>
      <tr>
        <td><%= move.name %></td>
        <td><%= move.pokemon_type_id %></td>
        <td><%= move.category %></td>
        <td><%= move.power %></td>
        <td><%= move.energy %></td>
        <td><%= move.cooldown %></td>
        <td><%= move.pvp_power %></td>
        <td><%= move.pvp_energy %></td>
        <td><%= move.pvp_turns %></td>
        <td><%= move.weather %></td>
        <td><%= move.damage_window_min %></td>
        <td><%= move.damage_window_max %></td>
        <td><%= link_to 'Show', move %></td>
        <td><%= link_to 'Edit', edit_move_path(move) %></td>
        <td><%= link_to 'Destroy', move, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Move', new_move_path %>

app/views/moves/new.html.erb
<h1>New Move</h1>

<%= render 'form', move: @move %>

<%= link_to 'Back', moves_path %>

app/views/moves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @move.name %>
</p>

<p>
  <strong>Pokemon type:</strong>
  <%= @move.pokemon_type_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @move.category %>
</p>

<p>
  <strong>Power:</strong>
  <%= @move.power %>
</p>

<p>
  <strong>Energy:</strong>
  <%= @move.energy %>
</p>

<p>
  <strong>Cooldown:</strong>
  <%= @move.cooldown %>
</p>

<p>
  <strong>Pvp power:</strong>
  <%= @move.pvp_power %>
</p>

<p>
  <strong>Pvp energy:</strong>
  <%= @move.pvp_energy %>
</p>

<p>
  <strong>Pvp turns:</strong>
  <%= @move.pvp_turns %>
</p>

<p>
  <strong>Weather:</strong>
  <%= @move.weather %>
</p>

<p>
  <strong>Damage window min:</strong>
  <%= @move.damage_window_min %>
</p>

<p>
  <strong>Damage window max:</strong>
  <%= @move.damage_window_max %>
</p>

<%= link_to 'Edit', edit_move_path(@move) %> |
<%= link_to 'Back', moves_path %>