config/routes.rb
Rails.application.routes.draw do
  resources :matchups
  resources :moves
  resources :pokemon_types
  resources :pokemon
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
	has_and_belongs_to_many :moves
	has_and_belongs_to_many :pokemon_types

	def	moves
		my_moves = super

		pokemon_type_ids = self.pokemon_types.pluck(:id)

		my_moves.each { |m| m.stab = ( self.pokemon_type_ids & [m.pokemon_type_id] ).present? }

		my_moves
	end

	def damage_output_vs(defending_pokemon = nil, attacking = true)
    	my_moves = moves

		my_best_moveset = best_moveset(attacking)

		fast_move = my_moves.detect { |m| m.name == my_best_moveset[0] } || Move.find_by_name("Splash")
		primary_charged_move = my_moves.detect { |m| m.name == my_best_moveset[1] } || Move.find_by_name("Struggle")
		secondary_charged_move = my_moves.detect { |m| m.name == my_best_moveset[3] }

		use_primary = true

		primary_scalar = 1
		secondary_scalar = 1

		if defending_pokemon
			primary_type = primary_charged_move.pokemon_type
			defending_types = defending_pokemon.pokemon_types
			matchups = Matchup.where("attacking_pokemon_type_id = ? AND defending_pokemon_type_id IN (?)",primary_type.id, defending_types.map(&:id))
			primary_scalar = matchups.map { |m| Matchup::EFFECTIVENESS[m.effectiveness] }.reduce(:*)
			primary_dps = my_best_moveset[2] * primary_scalar

			if secondary_charged_move
			secondary_type = secondary_charged_move.pokemon_type
			matchups = Matchup.where("attacking_pokemon_type_id = ? AND defending_pokemon_type_id IN (?)",secondary_type.id,defending_types.map(&:id))

			secondary_scalar = matchups.map { |m| Matchup::EFFECTIVENESS[m.effectiveness]}.reduce(:*)
			secondary_dps = my_best_moveset[4] * secondary_scalar
			
			use_primary = primary_dps > secondary_dps
			end

			# puts "The pokemon has a scalar of #{use_primary ? primary_scalar : secondary_scalar}!"
		end

		f = fast_move
		c = use_primary ? primary_charged_move : secondary_charged_move

	  uses = ( c.energy.to_f - (attacking ? 0 : f.energy.to_f ) ) / f.energy.to_f
	  damage = f.power.to_f * uses.to_f * ( f.stab ? 1.2 : 1 ) + c.power.to_f * (c.stab ? 1.2 : 1 )
		damage = damage * ( use_primary ? primary_scalar : secondary_scalar )
			
	  average_def = 142.0
		effective_def = defending_pokemon.try(:defense) || average_def

		damage = ((0.5 * damage * ( ( self.attack + 15 ) * Pokemon::CPM[40] ) / effective_def ) + 1)

		damage = ( damage.nan? || damage.nil? ) ? 0 : damage.floor

		if attacking
			time = f.cooldown.to_f * uses.to_f + c.cooldown.to_f
		else
			time = 2000.0 * uses.to_f + 2000.0
		end
		dps = damage.to_f / time.to_f * 1000.0

		if defending_pokemon
			enemy_health = (defending_pokemon.stamina + 15) * Pokemon::CPM[40]
		else
			enemy_health = 200
		end

		{
			win_in_n_seconds: enemy_health / dps.to_f
		}
	end
	
	def	movesets(attacking = true)
		my_moves = moves

		fast_moves = my_moves.select { |m| m.category == 'fast' }
		charged_moves = my_moves.select { |m| m.category == 'charged' }

		pairs = []

		out = []

		fast_moves.each do |f|
			charged_moves.each do |c|
				pairs << [f,c]
			end
		end

		pairs.each do |pair|
			f, c = pair
			uses = ( c.energy.to_f - (attacking ? 0 : f.energy.to_f ) ) / f.energy.to_f
			damage = f.power.to_f * uses.to_f * ( f.stab ? 1.2 : 1 ) + c.power.to_f * (c.stab ? 1.2 : 1 )
			
			average_def = 142.0

			damage = ((0.5 * damage * ( ( self.attack + 15 ) * Pokemon::CPM[40] ) / average_def ) + 1)

			damage = ( damage.nan? || damage.nil? ) ? 0 : damage.floor

			if attacking
			  time = f.cooldown.to_f * uses.to_f + c.cooldown.to_f
			else
				time = 2000.0 * uses.to_f + 2000.0
			end	
			dps = damage.to_f / time.to_f * 1000.0
			out << [f.name, c.name, dps, c.pokemon_type.name] if dps > 0
		end

		out = out.sort_by { |x| x[2] }.reverse

		out
	end

	def best_moveset(attacking = true)
    out = movesets(attacking)

		best_combo = out.first || ['Splash', 'Struggle', 0]

	  best_secondary_charged_move = out.detect { |x| x[0] == best_combo[0] and x[3] != best_combo[3] }

		if best_secondary_charged_move
      best_combo[3] = best_secondary_charged_move[1]
			best_combo[4] = best_secondary_charged_move[2]
    else
			best_combo[3] = nil
			best_combo.compact!
		end

		best_combo
	end

	def	max_cp(level = 40, attack_iv = 15, defense_iv = 15, hp_iv = 15)
		attack = self.attack + attack_iv
		defense = ( self.defense + defense_iv ) ** 0.5
		hp = ( self.stamina + hp_iv ) ** 0.5
		cpm = ( Pokemon::CPM[level] || 0.79030001 ) ** 2
		cp = [10,	(attack * defense * hp * cpm )  / 10 ].max.floor

		cp
	end

	# https://www.dragonflycave.com/pokemon-go/stats
	CPM = {
		37.5 => 0.776064962,
		38 =>  0.77893275,
		38.5 => 0.781790055,
		39 => 0.78463697,
		39.5 => 0.787473578,
		40 => 0.79030001
	}
end

app/models/pokemon_type.rb
class PokemonType < ApplicationRecord
	has_many :attacking_matchups, inverse_of: :attacking_pokemon_type, class_name: "Matchup", foreign_key: :attacking_pokemon_type_id
	has_many :defending_matchups, inverse_of: :defending_pokemon_type, class_name: "Matchup", foreign_key: :defending_pokemon_type_id

 default_scope { order(order: :asc) }


	has_and_belongs_to_many :pokemon
	has_many :moves
end

app/controllers/pokemon_controller.rb
class PokemonController < ApplicationController
  before_action :set_pokemon, only: [:show, :edit, :update, :destroy]

  # GET /pokemon
  # GET /pokemon.json
  def index
    @pokemon = Pokemon.all
  end

  # GET /pokemon/1
  # GET /pokemon/1.json
  def show
  end

  # GET /pokemon/new
  def new
    @pokemon = Pokemon.new
  end

  # GET /pokemon/1/edit
  def edit
  end

  # POST /pokemon
  # POST /pokemon.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully created.' }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemon/1
  # PATCH/PUT /pokemon/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully updated.' }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemon/1
  # DELETE /pokemon/1.json
  def destroy
    @pokemon.destroy
    respond_to do |format|
      format.html { redirect_to pokemon_index_url, notice: 'Pokemon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pokemon_params
      params.require(:pokemon).permit(:name, :attack, :defense, :stamina, :gen, :legendary, :caught, :pokedexNumber, :ancestor_id)
    end
end

app/helpers/pokemon_helper.rb
module PokemonHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/pokemon/_form.html.erb
<%= form_with(model: pokemon, local: true) do |form| %>
  <% if pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
        <% pokemon.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :attack %>
    <%= form.number_field :attack %>
  </div>

  <div class="field">
    <%= form.label :defense %>
    <%= form.number_field :defense %>
  </div>

  <div class="field">
    <%= form.label :stamina %>
    <%= form.number_field :stamina %>
  </div>

  <div class="field">
    <%= form.label :gen %>
    <%= form.number_field :gen %>
  </div>

  <div class="field">
    <%= form.label :legendary %>
    <%= form.check_box :legendary %>
  </div>

  <div class="field">
    <%= form.label :caught %>
    <%= form.check_box :caught %>
  </div>

  <div class="field">
    <%= form.label :pokedexNumber %>
    <%= form.number_field :pokedexNumber %>
  </div>

  <div class="field">
    <%= form.label :ancestor_id %>
    <%= form.number_field :ancestor_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pokemon/edit.html.erb
<h1>Editing Pokemon</h1>

<%= render 'form', pokemon: @pokemon %>

<%= link_to 'Show', @pokemon %> |
<%= link_to 'Back', pokemon_index_path %>

app/views/pokemon/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pokemon</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Attack</th>
      <th>Defense</th>
      <th>Stamina</th>
      <th>Gen</th>
      <th>Legendary</th>
      <th>Caught</th>
      <th>Pokedexnumber</th>
      <th>Ancestor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pokemon.each do |pokemon| %>
      <tr>
        <td><%= pokemon.name %></td>
        <td><%= pokemon.attack %></td>
        <td><%= pokemon.defense %></td>
        <td><%= pokemon.stamina %></td>
        <td><%= pokemon.gen %></td>
        <td><%= pokemon.legendary %></td>
        <td><%= pokemon.caught %></td>
        <td><%= pokemon.pokedexNumber %></td>
        <td><%= pokemon.ancestor_id %></td>
        <td><%= link_to 'Show', pokemon %></td>
        <td><%= link_to 'Edit', edit_pokemon_path(pokemon) %></td>
        <td><%= link_to 'Destroy', pokemon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pokemon', new_pokemon_path %>

app/views/pokemon/new.html.erb
<h1>New Pokemon</h1>

<%= render 'form', pokemon: @pokemon %>

<%= link_to 'Back', pokemon_index_path %>

app/views/pokemon/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pokemon.name %>
</p>

<p>
  <strong>Attack:</strong>
  <%= @pokemon.attack %>
</p>

<p>
  <strong>Defense:</strong>
  <%= @pokemon.defense %>
</p>

<p>
  <strong>Stamina:</strong>
  <%= @pokemon.stamina %>
</p>

<p>
  <strong>Gen:</strong>
  <%= @pokemon.gen %>
</p>

<p>
  <strong>Legendary:</strong>
  <%= @pokemon.legendary %>
</p>

<p>
  <strong>Caught:</strong>
  <%= @pokemon.caught %>
</p>

<p>
  <strong>Pokedexnumber:</strong>
  <%= @pokemon.pokedexNumber %>
</p>

<p>
  <strong>Ancestor:</strong>
  <%= @pokemon.ancestor_id %>
</p>

<%= link_to 'Edit', edit_pokemon_path(@pokemon) %> |
<%= link_to 'Back', pokemon_index_path %>