config/routes.rb
Rails.application.routes.draw do
  resources :matchups
  resources :moves
  resources :pokemon_types
  resources :pokemon
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/matchup.rb
class Matchup < ApplicationRecord
	belongs_to :attacking_pokemon_type, class_name: "PokemonType", foreign_key: "attacking_pokemon_type_id"
	belongs_to :defending_pokemon_type, class_name: "PokemonType", foreign_key: "defending_pokemon_type_id"

  default_scope { order(order: :asc) }

	# https://pokemongohub.net/post/wiki/type-effectiveness/
	
	EFFECTIVENESS = {
		"Immune" => 0.39,
		"Not Very Effective" =>	0.625,
		"Effective" => 1,
		"Super Effective" => 1.6
	}
end

app/controllers/matchups_controller.rb
class MatchupsController < ApplicationController
  before_action :set_matchup, only: [:show, :edit, :update, :destroy]

  # GET /matchups
  # GET /matchups.json
  def index
		@matchups = Matchup.all
  end

  # GET /matchups/1
  # GET /matchups/1.json
  def show
  end

  # GET /matchups/new
  def new
    @matchup = Matchup.new
  end

  # GET /matchups/1/edit
  def edit
  end

  # POST /matchups
  # POST /matchups.json
  def create
    @matchup = Matchup.new(matchup_params)

    respond_to do |format|
      if @matchup.save
        format.html { redirect_to @matchup, notice: 'Matchup was successfully created.' }
        format.json { render :show, status: :created, location: @matchup }
      else
        format.html { render :new }
        format.json { render json: @matchup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matchups/1
  # PATCH/PUT /matchups/1.json
  def update
    respond_to do |format|
      if @matchup.update(matchup_params)
				format.html { redirect_to action: :index, anchor: @matchup.id }
        # format.html { redirect_to @matchup, notice: 'Matchup was successfully updated.' }
        format.json { render :show, status: :ok, location: @matchup }
      else
        format.html { render :edit }
        format.json { render json: @matchup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matchups/1
  # DELETE /matchups/1.json
  def destroy
    @matchup.destroy
    respond_to do |format|
      format.html { redirect_to matchups_url, notice: 'Matchup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_matchup
      @matchup = Matchup.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def matchup_params
      params.require(:matchup).permit(:attacking_pokemon_type_id, :defending_pokemon_type_id, :effectiveness)
    end
end

app/helpers/matchups_helper.rb
module MatchupsHelper
end

app/views/matchups/_form.html.erb
<%= form_with(model: matchup, local: true) do |form| %>
  <% if matchup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(matchup.errors.count, "error") %> prohibited this matchup from being saved:</h2>

      <ul>
        <% matchup.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :attacking_pokemon_type_id %>
    <%= form.number_field :attacking_pokemon_type_id %>
  </div>

  <div class="field">
    <%= form.label :defending_pokemon_type_id %>
    <%= form.number_field :defending_pokemon_type_id %>
  </div>

  <div class="field">
    <%= form.label :effectiveness %>
    <%= form.text_field :effectiveness %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/matchups/edit.html.erb
<h1>Editing Matchup</h1>

<%= render 'form', matchup: @matchup %>

<%= link_to 'Show', @matchup %> |
<%= link_to 'Back', matchups_path %>

app/views/matchups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Matchups</h1>

<table>
  <thead>
    <tr>
      <th>Attacking pokemon type</th>
      <th>Defending pokemon type</th>
      <th>Effectiveness</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matchups.each do |matchup| %>
      <tr id="<%= matchup.id %>">
        <td><%= PokemonType.where(id: matchup.attacking_pokemon_type_id).pluck(:name).first %> is</td>

	<td>
	<%= form_with(model: matchup, local: true) do |form| %>
		<%= select_tag "matchup[effectiveness]", options_for_select(["Immune", "Not Very Effective", "Effective", "Super Effective"], matchup.effectiveness) %>
		<%= form.submit %>
	<% end %>
	</td>

        <td>against <%= PokemonType.where(id: matchup.defending_pokemon_type_id).pluck(:name).first %></td>

        <td><%= link_to 'Show', matchup %></td>
        <td><%= link_to 'Edit', edit_matchup_path(matchup) %></td>
        <td><%= link_to 'Destroy', matchup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Matchup', new_matchup_path %>

app/views/matchups/new.html.erb
<h1>New Matchup</h1>

<%= render 'form', matchup: @matchup %>

<%= link_to 'Back', matchups_path %>

app/views/matchups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Attacking pokemon type:</strong>
  <%= @matchup.attacking_pokemon_type_id %>
</p>

<p>
  <strong>Defending pokemon type:</strong>
  <%= @matchup.defending_pokemon_type_id %>
</p>

<p>
  <strong>Effectiveness:</strong>
  <%= @matchup.effectiveness %>
</p>

<%= link_to 'Edit', edit_matchup_path(@matchup) %> |
<%= link_to 'Back', matchups_path %>